### ISSUE TITLE
Api not showing

### ISSUE THREAD

**Issue by anirudhanishal** [Alexis06030631/yt_music_api#3]
Api not showing i want to try to paste url

**Comment by Alexis06030631** [comment]
@anirudhanishal Could you explain your problem in a little more detail?

**Comment by anirudhanishal** [comment]
How to download a files via url

**Comment by Alexis06030631** [comment]
You can use axios.get() to download a file via a url.
You can refer to this: [https://stackoverflow.com/a/53230807](https://stackoverflow.com/a/53230807).

If you find it useful, I can create a function that does it for you.

**Comment by Alexis06030631** [comment]
Update: you can now do this with the downloadManager.downloadAsFile() function documented here: [https://alexis06030631.github.io/yt_music_api/docs/method/downloadManager#function-downloadasfile](https://alexis06030631.github.io/yt_music_api/docs/method/downloadManager#function-downloadasfile)

Note: you need to update the module to version 1.3.0
