### ISSUE TITLE
Issue: Music.getRadioPlaylist() Returns the Current Song in the Playlist

### ISSUE THREAD

**Issue by DylanAkp** [Alexis06030631/yt_music_api#6]
**Current Behavior:**
The Music.getRadioPlaylist() method returns a list of Music object related to this Music but it also includes the current Music object itself

**Expected Behavior:**
The Music.getRadioPlaylist() method should return a list of related Music, excluding the current Music object from the list.

**Steps to Reproduce:**
Call the Music.getRadioPlaylist() method.
The returned playlist includes the Music object itself

**Comment by Alexis06030631** [comment]
Fixed as of version 2.0.0-beta.1.6.11
