### ISSUE TITLE
LOGIN_REQUIRED

### ISSUE THREAD

**Issue by wafarifki** [Alexis06030631/yt_music_api#8]
when i deploy to server, i getting this log and i cannot played the mp3.

this is log: 
> Error in /audio: {
>   code: 2004,
>   message: 'Song is not streamable, please check the unplayable reason',
>   details: 'LOGIN_REQUIRED'
> }

this is my code in /audio:
```
app.get('/audio/:videoId', async (req, res) => {
    const videoId = req.params.videoId;
    try {
        const playerData = await ytmusic.getPlayers(videoId);
        const audioUrl = await playerData.audios[0].url(); // Get the audio URL
        res.json({
            audioUrl
        });
    } catch (error) {
        console.error('Error in /audio:', error);
        res.status(500).json({
            error: 'Failed to retrieve audio URL'
        });
    }
});
```

can you help me for this?

**Comment by Alexis06030631** [comment]
Hi, this error normally appears when the song is not available in the country or it is private.

Can you give me the ID of the video/music so I can help you?

**Comment by wafarifki** [comment]
this is id = 9hjMIOIysng
this is youtube link = https://www.youtube.com/watch?v=9hjMIOIysng

thank you brother for your respons bro

**Comment by Alexis06030631** [comment]
> this is id = 9hjMIOIysng this is youtube link = https://www.youtube.com/watch?v=9hjMIOIysng
> 
> thank you brother for your respons bro

I'll invest in it and get back to you when the problem is solved.

**Comment by Alexis06030631** [comment]
## • Problem solved

#### Please update the module with the command `npm install ytmusic_api_unofficial@latest` (version: 2.0.6)

##### Details:
- The problem arose from an error on my part in the description and type of parameters allowed in the getPlayers() function
- The query parameter, which was calibrated to receive only the video ID, can now receive a direct link and extract the ID.

If you have any other problems or suggestions for improvement, please don't hesitate to contact me. I'll be happy to help.

**Comment by wafarifki** [comment]
bro.. very thank you for this solved bro.. you are the best.
